description: >
  Default executor

docker:
  - image: 'cimg/python:<<parameters.tag>>'

environment:
  ANSIBLE_FORCE_COLOR: "true"
  ANSIBLE_PIPELINING: "true"

parameters:
  tag:
    default: "3.11"
    description: >
      Pick a specific circleci/base image variant:
      https://hub.docker.com/r/cimg/python/tags
    type: string
